### ISSUE TITLE
[BUG] Unity splash screen logo isn't properly removed

### ISSUE THREAD

**Issue by ZeburaBlack** [kiraio-moe/USSR#10]
Unity 2022.3.10f1
USSR v1.1.5 win_x64

USSR outputs
( INFO ) Set hasProVersion = True | m_ShowUnitySplashLogo = False
( INFO ) Removing UnitySplash-cube...
( INFO ) Successfully removed the Unity splash screen.
( INFO ) Backup globalgamemanagers as [redacted]...
( INFO ) Writing changes to [redacted]...
( INFO ) Cleaning up temporary files...

but launching the game still plays the splash.

**Comment by kiraio-moe** [comment]
I do the same with #5. All the splash screen booleans are properly set, but the Unity splash screen logo is still there. There's error logic in my code and I'm currently making the patches.

**Comment by kiraio-moe** [comment]
Or there's anyone who interested to fix this?
