### ISSUE TITLE
[REQUEST] Support Decompression Fallback in WebGL

### ISSUE THREAD

**Issue by ULE7** [kiraio-moe/USSR#11]
So I turn on the splash logo at 2020.1.0 and made a webgl package, the USSR looked worked fine, However when I tried to open this webgl program it got stuck somehow, and never entered inside program. By the way I am using 1.1.5 USSR, already choose "All Sequential". 
I also tried 2022.3.0 unity it turns the same. I noticed I have marked "Decompression fallback" true in Player setting/Publishing setting which generate the .unityweb file instead of .gz files(gz is unusable for me). Seriously, I tried a lot times in different version of Unity, and never saw this USSR actually working even for once.........

**Comment by kiraio-moe** [comment]
Don't tick `Decompression Fallback`, currently it's not supported.

How about using `Brotli` compression? Did it work? If not, check the browser console for the error cause. You can also send the console screenshot and the `*.data` file here so I can experiment with it.

**Comment by ULE7** [comment]
![1](https://github.com/kiraio-moe/USSR/assets/112039649/297bd4bc-a521-4630-a0db-0350fe09c873)
I don't know how to use gz file actually(Not familiar with webgl stuff). My company demand all program must pack by form Decompression Fallback + Gzip otherwise it will not work. Also my computer can not open any webgl program directly somehow......
[web.zip](https://github.com/kiraio-moe/USSR/files/13445267/web.zip)

**Comment by kiraio-moe** [comment]
The game loaded successfully, although the splash screen are still there.

**Comment by kiraio-moe** [comment]
It's now fixed in #12. You can download the latest release, although the decompression fallback are still not supported.
Will be added in the future.

**Comment by ULE7** [comment]
[Build.zip](https://github.com/kiraio-moe/USSR/files/13464175/Build.zip)
![image](https://github.com/kiraio-moe/USSR/assets/112039649/792bd19d-e158-4997-a2a0-c2719c2c2b63)
Thanks for your remarkable work, but I can not open .gz program(screenshot) so I have to put here. This is the folder after I using USSR 1.1.6.

**Comment by kiraio-moe** [comment]
Use a local web server. Don't directly put it in the browser.
You can use Unity built-in web server in `YourUnityInstallation/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/SimpleWebServer.exe`. Run and it will show how to use the tool.

**Comment by kiraio-moe** [comment]
Oh, after you removed the splash screen, there will be a folder contains the decompressed WebGL data. I forgot to uncomment the code that will automatically remove them 😋

**Comment by ULE7** [comment]
> 使用本地 Web 服务器。不要直接放在浏览器中。您可以在 中使用 Unity 内置的 Web 服务器。运行，它将显示如何使用该工具。`YourUnityInstallation/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/SimpleWebServer.exe`

Thanks but can not open this exe lol

**Comment by kiraio-moe** [comment]
> Thanks but can not open this exe lol

Use this: https://uusoft.itch.io/unity-webgl-local-hoster
There will be an error at the startup, just continue.

**Comment by ULE7** [comment]
Wow this time it worked! However I believe the USSR is not working, instead it add the splash screen into the program. For example this is a program I pack it without the splash image (unity2020.1.0 cracked versio
[Build.zip](https://github.com/kiraio-moe/USSR/files/13470642/Build.zip)
n) it runs very good, after I use USSR on this program and open by webgl-local-hoster somehow the splash screen appear.

**Comment by kiraio-moe** [comment]
> Wow this time it worked! However I believe the USSR is not working, instead it add the splash screen into the program. For example this is a program I pack it without the splash image (unity2020.1.0 cracked versio [Build.zip](https://github.com/kiraio-moe/USSR/files/13470642/Build.zip) n) it runs very good, after I use USSR on this program and open by webgl-local-hoster somehow the splash screen appear.

There's no code to add splash screen whatsoever, instead it's check if there's any splash screen present. In my local changes, if there's only 1, it will auto-remove it.

**Comment by ULE7** [comment]
Ok I know whats going on , because I am using a cracked unity version which makes the USSR fail to do its job. After I switch to 2022.3.0, everything runs fine.  Thanks again bro, looking forward to the decompression fallback support !😋

**Comment by kiraio-moe** [comment]
> Ok I know whats going on , because I am using a cracked unity version which makes the USSR fail to do its job. After I switch to 2022.3.0, everything runs fine. Thanks again bro, looking forward to the decompression fallback support !😋

Yeah, I hope there's no any complicated problems while implementing it.

**Comment by kiraio-moe** [comment]
Ok, I have understand.
Decompression Fallback will produce `.unityweb` file which basically the same as `UnityWebData` (`.data`) file.
And if you use either GZip or Brotli compression, it's just GZip or Brotli file, but with custom file header.
