### ISSUE TITLE
( ERROR ) Unknown/Unsupported file type! (when trying to use globalgamemanagers)

### ISSUE THREAD

**Issue by wearrrrr** [kiraio-moe/USSR#14]
Hello! I'm trying to use the dotnet 6.0 linux x64 build of USSR, and encountering an issue where the software fails to recognize the globalgamemanagers file that came with the game upon compilation. Here is the file, 

https://mega.nz/file/9IInTbDL#Xjt0itmNgJ0HDqYm11fiq9eoFTUgfL7h5tGXDv-H4r0

I'm not sure why it's failing, as with manual tools I can read the file's contents just fine.
Thanks for reading :) If you need any other info, let me know!

**Comment by wearrrrr** [comment]
As an additional comment, the unity version is 2019.4.40f1

**Comment by kiraio-moe** [comment]
Thanks. I'll take a look at this.

**Comment by mmar58** [comment]
I also tried with the Windows built by Unity version 2022.3.13 and same result. Couldn't remove the splash screen
