### ISSUE TITLE
( ERROR ) Unknown/Unsupported file type! (when trying to use data.unity3d) Unity android build by editor version 2022.3.15

### ISSUE THREAD

**Issue by mmar58** [kiraio-moe/USSR#15]
( INFO ) unity3d file selected.
( INFO ) Loading class types package: K:\USSR-v1.1.6-net6.0-win-x64\classdata.tpk...
( INFO ) Loading asset class types database...
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'capacity')
   at System.Collections.Generic.List`1..ctor(Int32 capacity)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField, RefTypeManager refMan)
   at AssetsTools.NET.AssetTypeTemplateField.MakeValue(AssetsFileReader reader, RefTypeManager refMan)
   at USSR.Core.USSR.RemoveSplashScreen(AssetsManager assetsManager, AssetsFileInstance assetFileInstance) in E:\Projects\USSR\USSR.cs:line 533
   at USSR.Core.USSR.Main(String[] args) in E:\Projects\USSR\USSR.cs:line 307

**Comment by Jove125** [comment]
I had the same error "Unknown/Unsupported file type"
In my case problem with unity3dMagic array in USSR.cs script, 12th byte. In my "data.unity3d" file its 0x08, but in unity3dMagic - 0x07.
Workaround is to change this byte in "data.unity3d" (any hex editor), then run USSR and then change it back.
Or rebuild USSR with another unity3dMagic array.

**Comment by kiraio-moe** [comment]
> I had the same error "Unknown/Unsupported file type" In my case problem with unity3dMagic array in USSR.cs script, 12th byte. In my "data.unity3d" file its 0x08, but in unity3dMagic - 0x07. Workaround is to change this byte in "data.unity3d" (any hex editor), then run USSR and then change it back. Or rebuild USSR with another unity3dMagic array.

That's look interesting. What version of Unity you're using that produce different magic header?

**Comment by Jove125** [comment]
> > I had the same error "Unknown/Unsupported file type" In my case problem with unity3dMagic array in USSR.cs script, 12th byte. In my "data.unity3d" file its 0x08, but in unity3dMagic - 0x07. Workaround is to change this byte in "data.unity3d" (any hex editor), then run USSR and then change it back. Or rebuild USSR with another unity3dMagic array.
> 
> That's look interesting. What version of Unity you're using that produce different magic header?

2021.2.19f1

**Comment by kiraio-moe** [comment]
> > > I had the same error "Unknown/Unsupported file type" In my case problem with unity3dMagic array in USSR.cs script, 12th byte. In my "data.unity3d" file its 0x07, but in unity3dMagic - 0x08. Workaround is to change this byte in "data.unity3d" (any hex editor), then run USSR and then change it back. Or rebuild USSR with another unity3dMagic array.
> > 
> > 
> > That's look interesting. What version of Unity you're using that produce different magic header?
> 
> 2021.2.19f1

Ok, thanks. I'll add those bytes as unity3d identifier.
