### ISSUE TITLE
Unable to use on MacOS (M1)

### ISSUE THREAD

**Issue by activesand** [kiraio-moe/USSR#16]
Hey! I've been using this asset on Windows where it works perfectly but I'm completely unable to use it on MacOS (USSR-v1.1.6-net7.0-osx-arm64.zip) (I tried every other versions too), it always says: "X killed" (X being a random number), so I thought I had some issues with my terminal but from what I've searched for it seems like the issue is that the application is unsigned.

**Comment by kiraio-moe** [comment]
Signing the executable require me to buy some certificate from CA (Certificate Authorities) and thus I can't afford for that.

You can install a sandbox/VM or GitHub Codespace to run .NET app.

**Comment by activesand** [comment]
Hey @kiraio-moe, sorry for the long delay, for now I'm just building on mac, zipping to windows and doing the process there then zipping back to macos to deploy with xcode, working fine, just had issues with some unity versions so had to find the one working for both windows and mac and all good!

The link you sent is on old versions of macos, now it's some kind of popup that ask if you want to open anyway but it doesn't matter it always kills the process.

Thank you for your time!

**Comment by kiraio-moe** [comment]
> Hey @kiraio-moe, sorry for the long delay, for now I'm just building on mac, zipping to windows and doing the process there then zipping back to macos to deploy with xcode, working fine, just had issues with some unity versions so had to find the one working for both windows and mac and all good!
> 
> The link you sent is on old versions of macos, now it's some kind of popup that ask if you want to open anyway but it doesn't matter it always kills the process.
> 
> Thank you for your time!

Glad it's work 👍
I'll close this issue.
