### ISSUE TITLE
Unable to use USSR Tool 

### ISSUE THREAD

**Issue by DriveOneFirst** [kiraio-moe/USSR#2]
I have been trying to use USSR Tool Net 6 Version, but I'm encountering an issue. Every time I drag and drop my index.html file onto the .exe, it's giving me this error.

Could you please advise if I am doing something incorrectly or if there's a specific troubleshooting step I should follow to resolve this issue?

<img width="901" alt="Screenshot 2023-09-15 at 9 59 28 PM" src="https://github.com/kiraio-moe/USSR/assets/145124692/3614630e-105e-424e-bdeb-706da0cf3f08">

**Comment by kiraio-moe** [comment]
What Unity version are you using? Can you send me the `WebGL.data` file? I want to examine what's wrong with this specific version. If you're concern about the privacy, no need to send me. It's okay.

**Comment by DriveOneFirst** [comment]
I was using version 2023.3.30f1 (Silicon) on my Mac. I switched back to my original version, 2021.3. Since I've deleted the files, it would be difficult to attach the 'WebGL.data' file for the 2023 version.

**Comment by kiraio-moe** [comment]
It's okay, maybe the library I used can't recognize newer Unity, especially
for Mac.

Pada tanggal Sab, 16 Sep 2023 17.40, DriveOneFirst ***@***.***>
menulis:
