### ISSUE TITLE
Crash app after remove unity splash screen

### ISSUE THREAD

**Issue by kosecvn** [kiraio-moe/USSR#22]
## Image result
![image](https://github.com/kiraio-moe/USSR/assets/130122203/cf216e25-3134-4bfe-bdfa-5089ffd876c9)

**Comment by artur-pf** [comment]
exactly the same issue, any way to fix it by hand ?

**Comment by kiraio-moe** [comment]
> exactly the same issue, any way to fix it by hand ?

Of course you can, read this guide: https://github.com/kiraio-moe/remove-unity-splash-screen

**Comment by kiraio-moe** [comment]
@kosecvn Can you use the latest release? If it still not work, then the `TypeTree` curently not supporting that Unity version.
