### ISSUE TITLE
[QUESTION] How to run USSR on macOS?

### ISSUE THREAD

**Issue by MadMacMad** [kiraio-moe/USSR#24]
hello,
well not able to run it on Mac...
i'll open a terminal @ USSR ... than: sudo ./USSR
./USSR: command not found

something wrong?
thx
M

**Comment by kiraio-moe** [comment]
> hello, well not able to run it on Mac... i'll open a terminal @ USSR ... than: sudo ./USSR ./USSR: command not found
> 
> something wrong? thx M

Hi, go to Releases tab and download USSR according to your OS platform.
Extract, open a Terminal in the extracted folder and type `./USSR`

**Comment by MadMacMad** [comment]
yes ... but still the same...
also using sudo doesn't change anything still get:
./USSR: command not found
thx
M.

**Comment by kiraio-moe** [comment]
> yes ... but still the same... also using sudo doesn't change anything still get: ./USSR: command not found thx M.

Can you provide a short video, how you do it?

**Comment by MadMacMad** [comment]
sure ... did u test it on Mac OS X ? 
here is the Video:
https://www.smart-app.dev/Down/USSR-FAIL_MAC.mov

**Comment by kiraio-moe** [comment]
> sure ... did u test it on Mac OS X ?

No, I didn't have the device to do it. Generally, the steps is same for any kind if terminal.

> here is the Video: https://www.smart-app.dev/Down/USSR-FAIL_MAC.mov

It's weird. Does `USSR` executable present in the folder? How about drag n drop the executable directly?
Maybe change the permission `chmod +x`?

**Comment by ivanstepanovftw** [comment]
Hi, I see you struggling with building project. While README.md does not say anything about building, and the project does not have wiki to show how to build the project, always check .github folder for workflows. This project have the build.yml workflow file: https://github.com/kiraio-moe/USSR/blob/main/.github/workflows/build.yml
Here you see, that to build it you have to setup dotnet and build it using following command:
```shell
dotnet build -c Release --no-restore
```
Then it creates folder in the project somewhere, where executables can be found.

**Comment by ivanstepanovftw** [comment]
And I think you want to download yours already built executables from https://github.com/kiraio-moe/USSR/releases/tag/ussr-v1.1.7, not just downloading project sources as a zip file from the repository.

**Comment by thylaxene** [comment]
open USSR directory in the terminal and then at the prompt type "open USSR" you will run into the GateKeeper. So once it stops you opening the app go to System Settings and Privacy & Security and click the Open Anyway button which should be there. Run the open command again and accept you are happy to open the app.
