### ISSUE TITLE
Question on run Win11 24H2

### ISSUE THREAD

**Issue by greenozon** [kiraio-moe/USSR#28]
what is missed and to be installed under Win11 24H2?

```
C:\Users\user\Downloads\d8>ussr
Unity Splash Screen Remover v1.1.8

USSR is a tool to easily remove Unity splash screen. USSR didn't directly "hack" the Unity Editor, but the generated
build.

Before using USSR, make sure you have set the splash screen Draw Mode in Player Settings to All Sequential and backup
the target file below! For more information, visit USSR GitHub repo: https://github.com/kiraio-moe/USSR

HOW TO USE
Select the action below, find and select one of these files in your game data:
globalgamemanagers | data.unity3d | *.data | *.data.br | *.data.gz | *.data.unityweb


Opening File Picker...
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'nfd' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at NativeFileDialogSharp.Native.NativeFunctions.NFD_OpenDialog(Byte* filterList, Byte* defaultPath, IntPtr& outPath)
   at NativeFileDialogSharp.Dialog.FileOpen(String filterList, String defaultPath)
   at USSR.Core.USSR.OpenFilePicker() in E:\Projects\DOTNET\USSR\USSR.cs:line 401
   at USSR.Core.USSR.Main(String[] args) in E:\Projects\DOTNET\USSR\USSR.cs:line 31
```

same issue running either  USSR-v1.1.8-net8.0-win-x64.zip   or  USSR-v1.1.8-net6.0-win-x64.zip

**Comment by kiraio-moe** [comment]
Is there a file called `nfd.dll` in the extracted USSR folder? Or move USSR folder into different disk and run as Admin?

**Comment by greenozon** [comment]
Yes
maybe there are extra dependencies like MS VC runtime, etc?
this is a "just installed OS in VM", so no much stuff in it

![image](https://github.com/user-attachments/assets/7f2fe3e7-5833-40e4-981c-6d8cf89f6c3f)

**Comment by kiraio-moe** [comment]
I'm not sure. Haven't you try the `arm` build?
I've switched to another library that implement nfd. Can you try the build in here? https://github.com/kiraio-moe/USSR/actions/runs/10932074252

**Comment by greenozon** [comment]
nope, that was windows one (x64)
I've seen initial prints in the console, so it means the arch was correct

after I"ve installed MSVS 2022 17.11.4 the issue automagically  - gone

it means that the mfd library needs some extenral dependcy?

**Comment by kiraio-moe** [comment]
> it means that the mfd library needs some extenral dependcy?

No, just Windows API's itself.
