### ISSUE TITLE
[BUG] Crashed on Unity 2022.3.9f1

### ISSUE THREAD

**Issue by JESVN** [kiraio-moe/USSR#5]
![Snipaste_2023-09-25_15-33-38](https://github.com/kiraio-moe/USSR/assets/49424543/52e4b794-38d1-45cd-bbed-1b2d90d5c76e)
Show removal success
![Snipaste_2023-09-25_15-35-04](https://github.com/kiraio-moe/USSR/assets/49424543/bffcf457-26b4-4d5d-8198-1e0215f06e86)
But after opening the app, this window flashes by
![Snipaste_2023-09-25_15-33-49](https://github.com/kiraio-moe/USSR/assets/49424543/7d7b02aa-d8a8-4ffb-ae41-7c567561af7d)

**Comment by kiraio-moe** [comment]
Hmm. Interesting. Can you send me the generated build?

**Comment by JESVN** [comment]
> 唔。有趣的。你能把生成的版本发给我吗？ 我想测试一下。

[Test.zip](https://github.com/kiraio-moe/USSR/files/12733447/Test.zip)

**Comment by kiraio-moe** [comment]
> > Hmm. Interesting. Can you send me the generated build?
> > I want to test it out.
> 
> [Test.zip](https://github.com/kiraio-moe/USSR/files/12733447/Test.zip)

Thanks.

**Comment by kiraio-moe** [comment]
Hmm, I think this bug is caused by library which I used, AssetsTools.NET. Some users also reported in my YouTube channel that their Unity game is crashed when using updated Unity version which is only a few patches away.

**Comment by kiraio-moe** [comment]
Fixed in #12!
