### ISSUE TITLE
[REQUEST] Support File Name as Hashes in WebGL build

### ISSUE THREAD

**Issue by Spectralon** [kiraio-moe/USSR#7]
I used Unity 2022.3.10f1 to build a project with the following settings:

![image](https://github.com/kiraio-moe/USSR/assets/68746803/333bf1a2-490a-4ebe-8ec2-8b8ac1e39c41)

The _WebGl.data.gz_ file was named as _7e9c55bf336c56ec56ecff7b98edcd74d3a7.data.unityweb_. I opened this file with the Bandizip archiver and saw the following:

![image](https://github.com/kiraio-moe/USSR/assets/68746803/17d30961-84ff-46ff-8493-5a46f648c6a1)

As suggested in #4, I renamed it to _WebGl.data.gz_ and ran USSR, everything worked. Opening the generated file, I saw the following:

![image](https://github.com/kiraio-moe/USSR/assets/68746803/b12ea539-9fdd-4483-b422-4db1ccb986d2)

I then renamed this file back to _7e9c55bf336c56ecff7b98edcd74d3a7.data.unityweb_, but the game failed to load. I opened the renamed file again and was surprised:

![image](https://github.com/kiraio-moe/USSR/assets/68746803/a8e6dce9-8af0-45e7-bc6c-d46921393171)

Maybe this causes the issue, maybe not. In any case, removing the splash screen from builds with the "Name Files As Hashes" option enabled doesn't work.

**Comment by kiraio-moe** [comment]
Ah yes, I forgot those things 💀
For now, just disable it.

**Comment by kiraio-moe** [comment]
Sorry, MD5 is a one-way cryptographic hash function, so you can't reverse/crack the original value.
Disable `Name Files As Hashes` is a **MUST**.
