### ISSUE TITLE
[BUG] WebGL Error: Can't access the file because it is being used by another process

### ISSUE THREAD

**Issue by Corjn** [kiraio-moe/USSR#8]
Hey, I'm having this error with a webgl build : 

https://imgur.com/a/UvQyn0c

Works fine with a PC build (exact same app)
Any idea on how to solve this issue ? 
Thanks !

**Comment by kiraio-moe** [comment]
It's mostly a bug.
I'm currently working on the fixes in the dev branch. Hopefully it will fix it.
